### PR TITLE
Support Python 3.12 and 3.13.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Skip testing with the crypt module when it does not exist, like on Python 3.13 and Windows.  Fixes https://github.com/repoze/repoze.who/issues/44

Require ``legacy-cgi`` on Python 3.13 or higher so ``WebOb`` works.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@tseaver Could you review please? Thanks.

**Review by tseaver — APPROVED** [review]
Changes look great!  I didn't know about the `legacy-cgi` option, and so had shied away from trying to get 3.13 compatibility for any of the `repoze.*` packages.

**Comment by tseaver** [comment]
Note that this PR shouldn't close #44, as it doesn't really fix the issue:  it just lets CI succeed on 3.13.

**Comment by mauritsvanrees** [comment]
> Changes look great! I didn't know about the `legacy-cgi` option, and so had shied away from trying to get 3.13 compatibility for any of the `repoze.*` packages.

I found `legacy-cgi` in https://github.com/zopefoundation/zope.testbrowser/pull/108

**Pull request merged**
